
FROM node:18-alpine

# Install necessary packages including sudo, shadow, Python, Java 17, C++, and C
RUN apk add --no-cache sudo shadow python3 openjdk17 gcc g++ musl-dev

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install --production

COPY . .

# Create a new user and set the password
RUN useradd -m username && echo 'username:password' | chpasswd

# Grant the new user sudo privileges
RUN adduser username wheel && echo '%wheel ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers

# Switch to the new user
USER username

EXPOSE 3000

CMD ["node", "index.js"]
